### ISSUE TITLE
Error in open.connection(con, "rb") : Timeout was reached

### ISSUE THREAD

**Issue by michaelsanford** [maxconway/gsheet#11]
Greetings! I am experiencing a timeout when trying to pull a Google Sheet.

R version:
```
R version 3.3.3 (2017-03-06) -- "Another Canoe"
Platform: x86_64-w64-mingw32/x64 (64-bit)
```
I have configured my Google Sheet with "Anyone with the link can access, no sign-in required" permissions.

Perhaps pertinently, the sheet does contain a graph bound to full columns.

STR:
```
install.packages('gsheet')
library(gsheet)
gsheet2tbl('docs.google.com/spreadsheets/d/11...So');

`Error in open.connection(con, "rb") : Timeout was reached`
```

Also, I am behind a corporate proxy, but I was able to, say, _install_ the package without any additional configuration.

*Additional*:

I just tried to install the dev package this way:

```
install.packages('devtools')
#' etc...
package ‘devtools’ successfully unpacked and MD5 sums checked
devtools::install_github("maxconway/gsheet")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server
```

It's looking more likely that my corporate proxy is to blame.

Please do let me know if I have simply omitted something obvious, or if I should provide more diagnostic information.

**Comment by maxconway** [comment]
Hi Michael,

Yep it looks like the problem is probably in your network setup, or in your curl installation. If I were you I would try to run a few of the example cases in gsheet, something like `gsheet::gsheet2tbl('docs.google.com/spreadsheets/d/1I9mJsS5QnXF2TNNntTy-HrcdHmIF9wJ8ONYvEJTXSNo')`. That will probably fail, indicating that the issue isn't unique to your sheet. Assuming that your internet is generally working correctly I'd imagine that a problem with curl is a more likely culprit than use of a proxy, so if I were you I'd start out by reinstalling that. On linux that would involve reinstalling libcurl on the operating system, and then reinstalling the R bindings (the curl library), but I don't know the procedure for windows.

I haven't yet tested gsheet with sheets with graphs in them, (though I see no reason for that to create problems) so I'd be interested in your feedback on that when you get things working. 

Hope that's helpful
