### ISSUE TITLE
gsheet2tbl ignores characters within angle brackets (<>)

### ISSUE THREAD

**Issue by jbullock35** [maxconway/gsheet#5]
I am using gsheet 0.2.1 with R 3.1.0 (Windows, x64).  In general, it works flawlessly.  But it seems to ignore angle brackets and characters contained within those brackets.  For example, I have a sheet with the cell value `<test>hello`, and after I use `gsheet2tbl()`, I find that this value has been converted to `hello`.  

I can't tell why this is happening.  Is it a bug, or am I overlooking something?

**Comment by maxconway** [comment]
Hi,
Thanks for submitting this, its brought to light a couple of issues.
So I've had a look, and the issue is happening because I'm using rvest to parse the sheets, which I assume is seeing stuff in angle brackets as html tags. I'm not sure if that's the correct behavior for rvest, but it obviously isn't right for gsheet, so I've switched to using httr for parsing. I might remove all the rvest code entirely, but for now I've just done enough to fix this issue.

If you install again from github (`devtools::install_github("maxconway/gsheet")`) then you should find this problem fixed.

Tell me if that's helpful?

**Comment by jbullock35** [comment]
Thank you -- the changes are definitely helpful.  They seem to have fixed the problem.
